spring:
  datasource:
    # url: jdbc:h2:tcp://localhost:9099/~/testdb
    #    url: jdbc:h2:tcp://h2db:1521/~./testdb
    #    username: sa
    #    password: sa
    #    password: '{cipher}AQBxJvRfvqVqn++UALFX+I8N3qY2ZxK9dSiVFk3Gjfiqv0jedqDVLFEM27WeaBrXThtW6eKgGSbDa4w2h0mQt6G0scfXCEMylUjxTqdyQktxppa2UMNy5occXnc0oDe8h+wsAz+wjrFawSsY3+BkJxkCVBvW0PpqgcXFOvji0WUy5mKG85i24taxJ9hrOpigdt0wkg9UwUfSqe5aFc19eQiDdefKni0ir9IhIz4GUSpxErOACiWZDlphRGnfh4E/Cz1Vf7DW3hGMi2LhPsh1iaBnEQwzYqBIBGgKfspcF7xE09pbbpVLcf33dBlqdTPwYci/hnG1btpsax/fkIP6MeTTTH46HVjHVDWOT7oaPpGJyGRPJcgQ65+9lKNVPBd+Kwk='
    #    driver-class-name: org.h2.Driver
    url: jdbc:postgresql://user-db:54316/userlocaldb
    username: user_real
    password: '{cipher}AQBxuV51450yCph7gxm51lE/Z0QdwpoTFrVUpdEIkqGRZaZ0mFmfqyn63/vjI8Q/3A2zbQVxsjmT0AnczyJUlTzEiegMgUooAzuXZu1vgCHLMEbTMPD0myMPj1J7cjMk2xOf5MNoZ0V8N88g9omx3E0Hlw0ofO2mjYsBvICC9+5/gTHBux9KYfJvcphF7LqwZql/IqZM4/JXNH4bVQV7GOLivzQTa5fyAgNJ5nAgnWPJ4vs1Nu0+JPQjmxNF0/FW9mOxjDSCfv2Nf2O+Mmah+Tkqy96J4kFFuFTnRrUMPWdU4LT9yznKYbyIb/fyvBy5qNN+ZoMsvKmf2s9Zg3gCw4M1MlbkhMqmQs+AzMjku9+rsoK9NRnM2GlsRoe45SoITcU='
    driver-class-name: org.postgresql.Driver

token:
  expiration_time: 86400000
  #  secret: AQCcxKPovi3qWE4y7Apk8JvcIvf8wJNiPcJPkAMQJrzhJhZFecmIf7n1SgHb3wWVo4IOQtOXtDBRnoXDVEPd4AiHD+9ZC6CW3aXpGRAi0S/KUy8iENMm9CCatK0WZ07aU161dWekgyR2F3W8r1gLb98/TjvmbMnpX9Mi/onH/HViKEdGlGoQ28xbhNWIzqwLPjF+BIktRWdLVzmWdq/g2l2kHUR6/XrwSZsBbOHxAPBI45V7ROWGXuL43XbUOmZU3l/t6p1QHkl1SOFoDlhYEPUoXTvMVc441ManFZzghwctTQqpra66QPyTZxljyyBWdzjixeAxJLYXDSc6cjDZfWqi32D96SsbMoAfg19u7CLpvcKCui4T3EGtoFbQfY9clMBeDn7XlyFW2Hm5sgUi0DAsZeR+u0kJy3oHQmn+NqW67EvednkbJ/fSc2r9ROSh5MJN38fQGsh3UmHn5PrRMmkIlfp/2sm+oe2TSgnTtFhEb4OK9NfT7LL3dPx3Nitp5q548W3IDOGD98ULGEdEEj3S
  secret: '{cipher}AQCcxKPovi3qWE4y7Apk8JvcIvf8wJNiPcJPkAMQJrzhJhZFecmIf7n1SgHb3wWVo4IOQtOXtDBRnoXDVEPd4AiHD+9ZC6CW3aXpGRAi0S/KUy8iENMm9CCatK0WZ07aU161dWekgyR2F3W8r1gLb98/TjvmbMnpX9Mi/onH/HViKEdGlGoQ28xbhNWIzqwLPjF+BIktRWdLVzmWdq/g2l2kHUR6/XrwSZsBbOHxAPBI45V7ROWGXuL43XbUOmZU3l/t6p1QHkl1SOFoDlhYEPUoXTvMVc441ManFZzghwctTQqpra66QPyTZxljyyBWdzjixeAxJLYXDSc6cjDZfWqi32D96SsbMoAfg19u7CLpvcKCui4T3EGtoFbQfY9clMBeDn7XlyFW2Hm5sgUi0DAsZeR+u0kJy3oHQmn+NqW67EvednkbJ/fSc2r9ROSh5MJN38fQGsh3UmHn5PrRMmkIlfp/2sm+oe2TSgnTtFhEb4OK9NfT7LL3dPx3Nitp5q548W3IDOGD98ULGEdEEj3S'

gateway:
  #  ip: 127.0.0.1
  ip: apigateway-service

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order-is-empty: User's orders is empty.
