spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password: '{cipher}8e577a1709c899ae908f732cc979ea55c50507dd3d072194c7132eb04ebd568d'
    driver-class-name: org.h2.Driver

token:
  expiration_time: 86400000
  secret: ENC(gm4sGmKvZIwUsiSbmqtSSu+zrZU7kmeH)-local-user-service

gateway:
  ip: 127.0.0.1
