CREATE TABLE if not exists orders (
	created_at date NULL,
	qty int4 NOT NULL,
	unit_price int4 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	product_id varchar(120) NOT NULL,
	order_id varchar(255) NOT NULL,
	user_id varchar(255) NOT NULL,
	total_price int4 NULL,
	CONSTRAINT orders_order_id_key UNIQUE (order_id),
	CONSTRAINT orders_pkey PRIMARY KEY (id)
);