server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/onlydev7777/springboot-msa-3.0
          search-paths:
            - git-config-repo
          default-label: master
        bootstrap: true