server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/kj/IdeaProjects/inflearn-spring-boot-msa/springboot-msa-3.0/git-local-repo