spring:
  application:
    name: discoveryservice
  cloud:
    config:
      uri: http://localhost:8888
      name: ecommerce

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
